### PR TITLE
Add manifests to apps

### PR DESCRIPTION
**Pull request by kofalt**
Based on team discussion, this modifies the apps to use a manifest, which subsumes the info files.
Input directories have been modified to match. Can bump app version numbers on request.

### CODE REVIEW

**Comment by lmperry** [comment]
A fix for the timestamp behavior was committed to master (dad07dd1b2cda7e86ada2ed3a29fde46c049d84e). 

As you suggested, let's increment the version numbers across all of these gears to reflect this new behavior.

**Comment by kofalt** [comment]
Rebased and matched version number increments, but have not incremented the versions yet. Give the current diff a go, and if it looks good, we'll increment & merge later this week post code-freeze.

**Comment by lmperry** [comment]
LGTM. We do need to add manifests to the new brain-extraction gear, but that can be done after this PR lands.

**Comment by kofalt** [comment]
Cool. I'll be bumping the app version IDs and landing this soon.

**Pull request merged**
